### ISSUE TITLE
Suggestion: Fleetview link for fleets

### ISSUE THREAD

**Issue by RedBlaze42** [fleetyards/fleetyards#1198]
Firstly, I love your website !
But it's missing one little feature: being able to generate a fleetview link for corpo fleets.

I'll use your api and a little python script to do it but an integrated link and a API endpoint would be awesome !

Thank you again for your work.

**Comment by mortik** [comment]
Just to clarify you want a fleetview with the top down view of all ships inside your fleet as an direct linkable image for external use?

**Comment by RedBlaze42** [comment]
Just the link or a downloadable json file for Starship42 fleetview, just as the 3D button in the private hangar page. But if you have an idea for generating a linkable top-down image I'm down. (I can't find the Starship42 api)

**Comment by mortik** [comment]
Maybe we could do both the starship 42 link like the one on the Hangar should not be a problem - to generate an image on the server to link to will need a little bit more work

**Comment by RedBlaze42** [comment]
That'd be great.
I'll try to do the second part in python for my discord bot and I'll keep you in touch about the logic
