### ISSUE TITLE
Is it possible to translate the website?

### ISSUE THREAD

**Issue by GuguguBear** [fleetyards/fleetyards#1238]
I hope that in my spare time, I can help improve the best website in the world.
Interstellar citizen players cannot do without it.
I live in Hong Kong and I understand simplified and traditional languages.
I look forward to helping localize this website with the choice of traditional and simplified Chinese.
If you can, please tell me what you can do.
Thank you all for your efforts.

**Comment by GuguguBear** [comment]
Please let me know if there is any progress. Of course, we can also contact us through other means, such as Discord.
In short, my enthusiasm is still there, and I believe it will last a long time, please feel free to tell me how to do this.

**Comment by GuguguBear** [comment]
Please let me know if there is any progress. Of course, we can also contact us through other means, such as Discord.
In short, my enthusiasm is still there, and I believe it will last a long time, please feel free to tell me how to do this.

**Comment by mortik** [comment]
Long time no update here :(  But if you are still interessted in translating fleetyards i added fleetyards to crowdin https://crowdin.com/project/fleetyardsnet where the community can help to translate the page.

**Comment by GuguguBear** [comment]
Of course, my passion still lives on!

**Comment by mortik** [comment]
I added traditional and simplified Chinese to crowdin.

**Comment by GuguguBear** [comment]
> 我在crowdin中添加了繁体中文和简体中文。

Sorry for the late reply, busy with work.
I'll start working on the localization today, and I'll let you know here when it's fully finished.
