### ISSUE TITLE
Hangar: Restrict access for public hangar to specific accounts (e.g. only fleet members)

### ISSUE THREAD

**Issue by sazik** [fleetyards/fleetyards#1288]
Hi,

I want to be able to allow fleet members to view my hangar but not world accessible.

Might be handled with enhancement https://github.com/fleetyards/fleetyards/issues/1286 if there is an username filter.

Thanks

**Comment by mortik** [comment]
@sazik Since #1286 is resolved with #1287 is this still a needed Feature?

**Comment by sazik** [comment]
@mortik No it's fine. Thank you for your work. 👍
