### ISSUE TITLE
API: Get ship variants

### ISSUE THREAD

**Issue by MarvinMiles** [fleetyards/fleetyards#349]
Hi @mortik ! 

Thank you for your work!

Is it any possible way to get ship variants?
Many ships have prefixes in slug like "mustang-...", "constellation-...". So I could receive variants by splitting slug and using received prefix as "nameCont" filter in API requests. But this trick will not work with ships that doesn't have any prefixes like: 100i, 125A, 135C

So do you have any plans to implement ship variants feature to the API? :)

It could be another property in response, for example:
Request:  **.../v1/models/100i/**
Response:
```
{
...
"name": "100i",
"variants": ["125A", "135C"],
...
}
```

Or like your "images" system works:
Request: **.../v1/models/100i/variants**
Response:
```
[{
...
"name": "125A",
...
},
{
...
"name": "135C",
...
}]
```

Unfortunately I am not Ruby developer and can't help you with implementations like this.

**Comment by mortik** [comment]
Yes that looks good probably the second solution but i will have a look :) I might need to generate the needed Data myself because the official Shipmatrix has no Variant information currently but thats not a big deal.

**Comment by MarvinMiles** [comment]
Hey @mortik 

I figured out which key responsible for variants inside [RSI ship matrix REST object](https://robertsspaceindustries.com/ship-matrix/index). Key called **"chassis_id"**

I just checked it out: all Cutlasses have same id, all Auroras have same id and all Mustangs have same chassis id. So there is no doubt that this is it.

Did you know that? Will this help you somehow?)

**Comment by mortik** [comment]
Thanks :) i will have a look
