### ISSUE TITLE
Fleetchart does not show F8C Lightning (both variants)

### ISSUE THREAD

**Issue by paulpv** [fleetyards/fleetyards#363]
Steps:
1) Add F8C and/or F8C Executive to Hangar
2) Switch to Fleetchart view

Expected:
Ship(s) added in Step #1 are visible

Actual:
No F8C variants are visible

![screen shot 2018-11-06 at 2 58 19 pm](https://user-images.githubusercontent.com/1393897/48099491-8f66de80-e1d4-11e8-94c5-0269208a311f.png)
![screen shot 2018-11-06 at 2 58 43 pm](https://user-images.githubusercontent.com/1393897/48099496-955cbf80-e1d4-11e8-9b07-b35f36d8fa32.png)

**Comment by mortik** [comment]
Should be fixed. Since the F8C was manually added by me the needed length was missing.
