### ISSUE TITLE
documented list of ship slugs should be dynamic

### ISSUE THREAD

**Issue by paulpv** [fleetyards/fleetyards#364]
The list of ship slug names is documented at:
https://api.fleetyards.net/v1#header-ships-list

This list doesn't contain recent ships (such as Kraken and Valkyrie).

It would be nice if this documented list could dynamically be kept up to date.

**Comment by mortik** [comment]
Since the Documentation is staticly generated before deployment and only there this is not possible.

I could provide an endpoint which returns a list of all Slugs.
