### ISSUE TITLE
Support viewing 3D models in VR

### ISSUE THREAD

**Issue by paulpv** [fleetyards/fleetyards#365]
I realize that FleetYard shells out to http://www.starship42.com/fleetview/?source=FleetYards&type=matrix...

I am posting here because perhaps there is a VR solution that could work separately from to starship42/fleetview, but I suspect this issue may get resolved to just wait for starship42/fleetview support VR.

I am the author of the poorly advertised Fleet VieweR https://github.com/swooby/fleet-viewer (created 2017/07/28 and first functional around 2017/08/12).
This app has no relationship to Lundfoci's http://starship42.com/fleetview/
I would CC him in this issue if I knew his GitHub username.

My Fleet VieweR app supported only Google Daydream (Android & iOS) and was written in Unity.
I ran in to limitations displaying large fleets (too many polys).
I mitigated this a bit with 5 LODs, but I also needed to integrate or implement dynamic occlusion culling to get this to me usable, but I never got around to this.
In February 2018 I got a bit burned out and moved on to writing other SC tools that interested me, but I am seriously considering picking back up VR fleet viewing.

I am looking for a better way to support more VR devices (Oculus, Vive, etc) and better support Web browsers.
I am not currently sure what options are available, but I am willing to look in to this and hope that there is something semi-off-the-shelf that can make implementation "fairly" easy (yes, I realize I may be dreaming).
Or I will be re-writing my app from scratch to better support multiple platforms.

Perhaps @mortik or Lundfoci know of a good way to support this in FleetYard or starship42/fleetview?

Let us please converse a bit (either here on in private email) to see if there is anything we can do together to make this possible.

Thanks!
Pv

**Comment by mortik** [comment]
Hey, 

it would be best if you would contact lundfoci directly via Twitter about this https://twitter.com/Lundfoci, currently FleetYards only embeds the 3D Viewer from starship42.com. The right person to talk about VR for the 3D Viewer is him :)

Best,
Marten
