### ISSUE TITLE
3D (starship42/fleetview) URL is limited to 30 ships

### ISSUE THREAD

**Issue by paulpv** [fleetyards/fleetyards#368]
Refer to the following test account:
* https://www.fleetyards.net/hangar/NightVsKnight - 31 100i ships

The generated "3D" URL is:
`http://www.starship42.com/fleetview/?source=FleetYards&type=matrix&s%5B0%5D=100i&s%5B1%5D=100i&s%5B2%5D=100i&s%5B3%5D=100i&s%5B4%5D=100i&s%5B5%5D=100i&s%5B6%5D=100i&s%5B7%5D=100i&s%5B8%5D=100i&s%5B9%5D=100i&s%5B10%5D=100i&s%5B11%5D=100i&s%5B12%5D=100i&s%5B13%5D=100i&s%5B14%5D=100i&s%5B15%5D=100i&s%5B16%5D=100i&s%5B17%5D=100i&s%5B18%5D=100i&s%5B19%5D=100i&s%5B20%5D=100i&s%5B21%5D=100i&s%5B22%5D=100i&s%5B23%5D=100i&s%5B24%5D=100i&s%5B25%5D=100i&s%5B26%5D=100i&s%5B27%5D=100i&s%5B28%5D=100i&s%5B29%5D=100i`

Note that the URL ends in `%5B29%5D` for 30 ships, not `%5B30%5D` for 31 ships.
I have two non-test accounts with 44 and 58 ships each, and their 3D URLs also end at the 30th ship.  
This tells me that the 3D URL is limited to 30 models.

I have looked through the code at https://github.com/fleetyards/app/blob/master/app/javascript/frontend/pages/Hangar/index.vue#L318
```javascript
starship42Url() {
      const shipList = this.vehicles.map(vehicle => vehicle.model.rsiName)
      const data = { source: 'FleetYards', type: 'matrix', s: shipList }
      const startship42Params = qs.stringify(data)
      return `http://www.starship42.com/fleetview/?${startship42Params}`
    }
```
... and where it calls `qs.stringify(data)`, and then the code for `qs.stringify` (https://github.com/ljharb/qs/blob/master/lib/stringify.js), but I do not see where the 30 item limit is either directly or indirectly enforced.

```
starship42Url: function() {
                var t = {
                    source: "FleetYards",
                    type: "matrix",
                    s: this.vehicles.map(function(t) {
                        return t.model.rsiName
                    })
                };
                return "http://www.starship42.com/fleetview/?" + Ti.a.stringify(t)
            }
```

Perhaps it is a problem with how the data is being passed [aka: data.length?]?

**Comment by paulpv** [comment]
Odd: Nothing in querystring seems to have an arbitrary limit of 30:
```javascript
var qs = require('qs')
var vehicles = [];
for(var i=0; i < 64; i++) {
  vehicles[i] = {
    model: {
      rsiName: 'ship' + i
    }
  }
}
function starship42Url() {
  const shipList = vehicles.map(vehicle => vehicle.model.rsiName)
  const data = { source: 'FleetYards', type: 'matrix', s: shipList }
  const startship42Params = qs.stringify(data)
  return `http://www.starship42.com/fleetview/?${startship42Params}`
}
console.log('starship42Url(): ' + starship42Url())
```
`starship42Url(): http://www.starship42.com/fleetview/?source=FleetYards&type=matrix&s%5B0%5D=ship0&s%5B1%5D=ship1&s%5B2%5D=ship2&s%5B3%5D=ship3&s%5B4%5D=ship4&s%5B5%5D=ship5&s%5B6%5D=ship6&s%5B7%5D=ship7&s%5B8%5D=ship8&s%5B9%5D=ship9&s%5B10%5D=ship10&s%5B11%5D=ship11&s%5B12%5D=ship12&s%5B13%5D=ship13&s%5B14%5D=ship14&s%5B15%5D=ship15&s%5B16%5D=ship16&s%5B17%5D=ship17&s%5B18%5D=ship18&s%5B19%5D=ship19&s%5B20%5D=ship20&s%5B21%5D=ship21&s%5B22%5D=ship22&s%5B23%5D=ship23&s%5B24%5D=ship24&s%5B25%5D=ship25&s%5B26%5D=ship26&s%5B27%5D=ship27&s%5B28%5D=ship28&s%5B29%5D=ship29&s%5B30%5D=ship30&s%5B31%5D=ship31&s%5B32%5D=ship32&s%5B33%5D=ship33&s%5B34%5D=ship34&s%5B35%5D=ship35&s%5B36%5D=ship36&s%5B37%5D=ship37&s%5B38%5D=ship38&s%5B39%5D=ship39&s%5B40%5D=ship40&s%5B41%5D=ship41&s%5B42%5D=ship42&s%5B43%5D=ship43&s%5B44%5D=ship44&s%5B45%5D=ship45&s%5B46%5D=ship46&s%5B47%5D=ship47&s%5B48%5D=ship48&s%5B49%5D=ship49&s%5B50%5D=ship50&s%5B51%5D=ship51&s%5B52%5D=ship52&s%5B53%5D=ship53&s%5B54%5D=ship54&s%5B55%5D=ship55&s%5B56%5D=ship56&s%5B57%5D=ship57&s%5B58%5D=ship58&s%5B59%5D=ship59&s%5B60%5D=ship60&s%5B61%5D=ship61&s%5B62%5D=ship62&s%5B63%5D=ship63`

**Comment by mortik** [comment]
i will have a look there is not limit in the url generation, when we implemented this feature i tested it with accounts which had all ships multiple times and it worked... something seems to have changed.

**Comment by mortik** [comment]
I found the Issue :D its the Pagination on the Page you are only getting 30 Ships per Page ^^ I fixed this and the url should now include every Ship in your Hangar.
