### ISSUE TITLE
Endeavor modules

### ISSUE THREAD

**Issue by MarvinMiles** [fleetyards/fleetyards#374]
Hey @mortik  👍 

List of ships that includes Endeavor modules looks like a mess.

How about put array of modules to each ship model like a hardpoints does. Or create new api page  v1/models/slug/modules for example

What do you think?

**Comment by mortik** [comment]
Yes... now that i see them in the list they seem missplaced... hmm i wanted a way to allow people to add them to their Hangar but maybe that needs to be more like a Equipment thing for Ships in your Hangar.

I will rework it to be a list on the model called modules and show them on the ship detail page :)

Thanks for the Feedback :) 👍
